security:
    access_denied_url: /login
    encoders:
        AppBundle\Entity\User: bcrypt

    role_hierarchy:
        ROLE_ADMIN:     ROLE_USER
        ROLE_SUPER_ADMIN:   ROLE_ADMIN

    # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers
    providers:
        fos_userbundle:
            id: fos_user.user_provider.username_email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        login:
            host: api\.ojbento\.fr
            pattern: ^/login
            stateless: true
            logout: true
            anonymous: true
            json_login:
                check_path: /login_check
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure
                
        auth_register:
            host: api\.ojbento\.fr
            pattern: ^/auth/register
            stateless: true
            anonymous: true
            provider: fos_userbundle

        api:
            host: api\.ojbento\.fr
            pattern: ^/
            stateless: true
            anonymous: true
            provider: fos_userbundle
            guard:
                authenticators:
                    - lexik_jwt_authentication.jwt_token_authenticator

        main:
            host: admin\.ojbento\.fr
            access_denied_handler: App\Security\AccessDeniedHandler
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_token_generator: security.csrf.token_manager
            logout: true
            anonymous: true

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY , host: admin\.ojbento\.fr }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY , host: admin\.ojbento\.fr }
        - { path: ^/register, roles: IS_AUTHENTICATED_ANONYMOUSLY, host: admin\.ojbento\.fr }
        - { path: ^/redirectTo, roles: IS_AUTHENTICATED_ANONYMOUSLY, host: ojbento\.fr/login }
        - { path: ^/type, roles: IS_AUTHENTICATED_ANONYMOUSLY, host: api\.ojbento\.fr }
        - { path: ^/, role: ROLE_ADMIN , host: admin\.ojbento\.fr }
