swiftmailer:
    delivery_addresses: ['ddoussain@gmail.com']
    transport: smtp
    encryption: ssl
    host: smtp.gmail.com
    username: ddoussain@gmail.com
    password: Dorian130296du33SISI*
    spool: { type: 'memory' }
