swiftmailer:
    delivery_addresses: ['pierretisserand31@gmail.com']
    transport: smtp
    encryption: ssl
    host: smtp.gmail.com
    username: pierretisserand31@gmail.com
    password: T@les070890
    spool: { type: 'memory' }
