to_ng:
    path: /
    host: 'pi-ti.fr'
    defaults:
        url: 'http://ojbento.pi-ti.fr'

controllers:
    host: 'admin.ojbento.pi-ti.fr'
    resource: ../../src/Controller/
    type: annotation

api_auth_login:
    host: 'api.ojbento.pi-ti.fr'
    path: /login_check
    methods: [POST]

api_controller:
    host: 'api.ojbento.pi-ti.fr'
    resource: ../../src/ApiController/
    type: annotation
